name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/driver-backend
            git pull origin main
            npm install --production
            pm2 stop all
            pm2 start server.js --name "azhai-backend" || pm2 restart azhai-backend
            pm2 save
            echo "✅ Deploy complete. Server restarted."
            pm2 list
